name: CI

# Controls when the action will run. Triggers the workflow on pushes to main or on pull request events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

# PR workflow that builds but does not push an image
jobs:
  build_commit:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - uses: actions/checkout@v2
      - name: Get shortsha
        id: vars
        run: |
          if [ -z "$EVENT_SHA" ]; then SHORT_SHA=${GITHUB_SHA::8}; else SHORT_SHA=${EVENT_SHA::8}; fi
          echo ::set-output name=sha_short::${SHORT_SHA}
        env:
          EVENT_SHA: ${{ github.event.client_payload.sha }} 
      - name: Print shortsha
        run: |
          echo $SHORTSHA
        env: 
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}     
      - uses: docker/setup-buildx-action@v2
        name: Setup Docker Builds
      - uses: docker/login-action@v2
        name: Log in to docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Build & push commit tagged Docker image
        with:
          context: wdc
          push: false
          tags: taccdash/democratizingdata-wdc:${{ steps.vars.outputs.sha_short }},taccdash/democratizingdata-wdc:dev
          args: |
            APIURL=https://dev.democratizingdata.tacc.utexas.edu